# Generated by Django 5.0.4 on 2024-04-12 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_alter_comment_content_alter_post_content_postversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalPostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.post')),
            ],
        ),
    ]
