# Generated by Django 5.0.4 on 2024-04-12 12:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_originalpostcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalpostcontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
